# Generated by Django 4.2.4 on 2023-08-02 02:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
